FROM oven/bun:latest

WORKDIR /usr/app/src
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./apps/web ./apps/web
COPY ./turbo.json ./turbo.json


RUN bun install



CMD [ "bun","run","start:web" ]
